<h2>Auto Generated label</h2>

<p>This label content will be autogenerated from the label definitions</p>

{include file=edit_label/info.tpl}

{form_open name=form_edit_label to="edit_labels/edit_auto"}
{include file=edit_label/hidden.tpl}
{form_submit name=submit msg='Generate label'}
{form_end}