
<h2>Auto Generated label</h2>

<p>This label content will be autogenerated from the label definitions</p>

{include file=new_label/info.tpl}

{form_open name=form_add_label to="label_sequence/add_auto_label"}
{include file=new_label/hidden.tpl}
{form_submit name=submit msg='Generate label'}
{form_end}

