
<ul>
  <li>Name: {$label.name}</li>
  <li>Sequence name: {$sequence.name}</li>
  {if $label.code}
  <li>Label can be autogenerated</li>
  {/if}
</ul>

<script>

{to_js var=label value=$label}
var validate_new_label_form = null;

{literal}
$(document).ready(function () {
  function checkResponse(responseText, statusText) {
    var resp = $.evalJSON(responseText);

    if(resp == true) {
      if(label.multiple == 0) {
        reload_addable_list();
      }

      if(label.must_exist == 1) {
        reload_missing_list();
      }

      reload_labels_list();
    } else {
      alert(responseText);
    }

    self.parent.tb_remove();
  }

  $('#form_add_label').ajaxForm({
    success: checkResponse,
    beforeSubmit: function (data, form) {
      return $(form).valid();
    }
  });
});
{/literal}
</script>
