<?php

define('VALIDATE_SCRIPT', 'jquery.validate.js');
define('DATEPICKER_SCRIPT', 'ui/ui.datepicker.js');
define('DATEPICKER_THEME', 'themes/default/ui.datepicker.css');
define('UPLOAD_DIRECTORY', '../uploads/');
define('CONFIRM_SCRIPT', 'jquery.confirm-1.2.js');
define('JEDITABLE_SCRIPT', 'jquery.jeditable.js');
define('JSON_SCRIPT', 'jquery.json-1.3.js');
define('SESSION_SCRIPT', 'jquery.session.js');
define('APPENDDOM_SCRIPT', 'jquery.appendDom.js');
define('AUTOCOMPLETE_SCRIPT', 'jquery.autocomplete.js');
define('AUTOCOMPLETE_THEME', 'jquery.autocomplete.css');
define('THICKBOX_SCRIPT', 'jquery.thickbox.js');
define('THICKBOX_THEME', 'jquery.thickbox.css');
define('MYGRID_SCRIPT', 'jquery.mygrid.js');
define('MYGRID_THEME', 'jquery.mygrid.css');
define('IMPROMPTU_SCRIPT', 'jquery.impromptu.js');
define('AJAXIMPROMPTU_SCRIPT', 'jquery.ajaximpromptu.js');
define('IMPROMPTU_THEME', 'jquery.impromptu.css');
define('FORM_SCRIPT', 'jquery.form.js');
define('PLUSMINUS_SCRIPT', 'jquery.plusminus.js');
define('ZOOM_SCRIPT', 'jquery.zoom.js');
define('COOKIE_SCRIPT', 'jquery.cookie.js');
define('SELECTBOXES_SCRIPT', 'jquery.selectboxes.js');
define('GETPARAMS_SCRIPT', 'jquery.getParams.js');
define('LIVEQUERY_SCRIPT', 'jquery.livequery.js');
define('TEXTGROW_SCRIPT', 'textgrow.js');
define('BLOCKUI_SCRIPT', 'jquery.blockUI.js');
