<ul>
  <li>Name: <a href="{site}/label/view/{$label.id}">{$label.name}</a></li>
  <li>Sequence name: {$sequence.name}</li>
  {if $label.code}
  <li>Label can be autogenerated</li>
  {/if}
</ul>

<div id="label_error" {display_none}><span id="label_error_txt"></span></div>